package bham.bioshock.communication;

/**
 * Interface for handling commands generated by server or client
 * 
 * @author Jan Dabrowski
 */
public interface ActionCommand {

	/**
	 * @return short string unique for a command
	 */
	public String getText();

	/**
	 * @return number of arguments that the command require
	 */
	public int getNum();
}
